version: "3.9"
services:
  mongodb:
    image: mongo:7.0
    container_name: food_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db

  cassandra:
    image: cassandra:4.1
    container_name: food_cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: FoodDeliveryCluster
      CASSANDRA_DC: datacenter1
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 10

  redis:
    image: redis:7.2
    container_name: food_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  neo4j:
    image: neo4j:5
    container_name: food_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password123
    volumes:
      - neo4j_data:/data


volumes:
  mongodb_data:
  cassandra_data:
  redis_data:
  neo4j_data:

